# Generated by Django 2.2.6 on 2019-10-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('author', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tech_Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='Date Created')),
                ('author', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('features', models.ManyToManyField(to='business_features.Feature')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
